fastlane_version "2.98.0"
default_platform :ios

platform :ios do
  before_all do |lane, options|
	ENV["XCODE_PROJ"] = "./ios/Runner.xcodeproj"
	ENV["APP_ID"] = "com.nflx-partiers.party-hardy"
	ENV["PLIST"] = "./ios/Runner/Info.plist"
	ENV["APP_NAME"] = "Netflix Party Harder"
  end

	lane :everything do
		setup
		compile
		deploy
	end

  lane :setup do
	setup_project
  end

  lane :compile do
	build
  end

  lane :deploy do
	hockey_upload
  end

  private_lane :setup_project do


	create_keychain(
		name: "party-hardy_keychain",
		password: "meow",
		default_keychain: true,
		unlock: true,
		timeout: 3600,
		lock_when_sleeps: false
	)
  end

  private_lane :build do
	match(
		type: "party-hardy",
		readonly: is_ci,
	  	keychain_name: "party-hardy_keychain",
	  	keychain_password: "meow"
  	)

	enable_automatic_code_signing(
      path: ENV["XCODE_PROJ"]
    )

	build_app(
		scheme: "party-hardy",
		project: ENV["XCODE_PROJ"]
	)

  end

  private_lane :hockey_upload do
  	hockey(
	  	api_token: ENV["HOCKEY_TOKEN"],
	  	create_status: "2",
	  	ipa: "party-hardy.ipa",
	  	notes: ENV["RELEASENOTES"]
	)
  end
end
